//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerEntities : DbContext
    {
        public SchedulerEntities()
            : base("name=SchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TScheduler> TSchedulers { get; set; }
        public virtual DbSet<TSchedulerExecution> TSchedulerExecutions { get; set; }
        public virtual DbSet<TSchedulerLog> TSchedulerLogs { get; set; }
        public virtual DbSet<TSchedulerSetting> TSchedulerSettings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
