//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSchedulerSetting
    {
        public int SchedulerSettingsId { get; set; }
        public int SchedulerId { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<int> DailyRecurrence { get; set; }
        public Nullable<int> HourlyRecurrence { get; set; }
        public Nullable<int> SelectedDayOfWeek { get; set; }
        public Nullable<int> SelectedMonth { get; set; }
        public Nullable<int> SelectedDayOfMonth { get; set; }
    
        public virtual TScheduler TScheduler { get; set; }
    }
}
