//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TScheduler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TScheduler()
        {
            this.TSchedulerExecutions = new HashSet<TSchedulerExecution>();
            this.TSchedulerSettings = new HashSet<TSchedulerSetting>();
        }
    
        public int SchedulerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> PartnerType { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RecurrenceFrequency { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSchedulerExecution> TSchedulerExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSchedulerSetting> TSchedulerSettings { get; set; }
    }
}
