//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSchedulerExecution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSchedulerExecution()
        {
            this.TSchedulerLogs = new HashSet<TSchedulerLog>();
        }
    
        public int SchedulerExecutionId { get; set; }
        public int SchedulerId { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TScheduler TScheduler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSchedulerLog> TSchedulerLogs { get; set; }
    }
}
