//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSchedulerLog
    {
        public int SchedulerLogId { get; set; }
        public int SchedulerExecutionId { get; set; }
        public int SchedulerId { get; set; }
        public Nullable<System.DateTime> ExecutionTimestamp { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> ActionType { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> PartnerType { get; set; }
        public Nullable<int> PartnerId { get; set; }
    
        public virtual TSchedulerExecution TSchedulerExecution { get; set; }
    }
}
